2 types of Word Embedding - Word2Vec, Glove

Word Embedding- 

How to represent words in vector form such that 2 vectors close to each other represent 2 similar words using vectors. OHE for every single word not possible.

Man will have 0.789
Woman will have 0.787
Gender will have 0.700
Such maxtrix which shows link between 2 vectors is called Feature Representation Word Embedding

In BOW and TF-IDF, we lose semantic info ie its actual meaning as it deals only with counting of words and how many times repeation happens. So we use Word Embedding

But In Word2Vec, we focus on local words surrounding the word and not the entire corpus. If King in 1st sentence, royal after 1000 words, Word2Vec fails to predict here. Solution is Glove(Global Vectors) which uses global corpus

GloVe constructs an explict word-context or word co-occrance matrix across entire corpus of words and results in better embedding. 

In GloVe, 'solid' and 'ice' is close then 'steam' but 'gas' is close to 'steam'

#**Word2vec**

In [ ]:
import nltk
nltk.download('punkt')
nltk.download('stopwords')

from gensim.models import Word2Vec
from nltk.corpus import stopwords

import re

paragraph = """I have three visions for India. In 3000 years of our history, people from all over 
               the world have come and invaded us, captured our lands, conquered our minds. 
               From Alexander onwards, the Greeks, the Turks, the Moguls, the Portuguese, the British,
               the French, the Dutch, all of them came and looted us, took over what was ours. 
               Yet we have not done this to any other nation. We have not conquered anyone. 
               We have not grabbed their land, their culture, 
               their history and tried to enforce our way of life on them. 
               Why? Because we respect the freedom of others.That is why my 
               first vision is that of freedom. I believe that India got its first vision of 
               this in 1857, when we started the War of Independence. It is this freedom that
               we must protect and nurture and build on. If we are not free, no one will respect us.
               My second vision for India’s development. For fifty years we have been a developing nation.
               It is time we see ourselves as a developed nation. We are among the top 5 nations of the world
               in terms of GDP. We have a 10 percent growth rate in most areas. Our poverty levels are falling.
               Our achievements are being globally recognised today. Yet we lack the self-confidence to
               see ourselves as a developed nation, self-reliant and self-assured. Isn’t this incorrect?
               I have a third vision. India must stand up to the world. Because I believe that unless India 
               stands up to the world, no one will respect us. Only strength respects strength. We must be 
               strong not only as a military power but also as an economic power. Both must go hand-in-hand. 
               My good fortune was to have worked with three great minds. Dr. Vikram Sarabhai of the Dept. of 
               space, Professor Satish Dhawan, who succeeded him and Dr. Brahm Prakash, father of nuclear material.
               I was lucky to have worked with all three of them closely and consider this the great opportunity of my life. 
               I see four milestones in my career"""



# Pre-processing the data
text = re.sub(r'\[[0-9]*\]',' ',paragraph) # removing numbers
text = re.sub(r'\s+',' ',text) # special char and extra spaces
text = text.lower()
text = re.sub(r'\d',' ',text) 
text = re.sub(r'\s+',' ',text)

# Preparing the dataset
sentences = nltk.sent_tokenize(text) # can skip

sentences = [nltk.word_tokenize(sentence) for sentence in sentences]

for i in range(len(sentences)):
    sentences[i] = [word for word in sentences[i] if word not in stopwords.words('english')]
    
    
# Training the Word2Vec model
model = Word2Vec(sentences, min_count=1) # if min count of word is < 1 then drop the word

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
vectors = model.wv.vectors # will give word embedding, wv-word vector
print(vectors)


# keys = model.wv.vocab.keys() # actual individual words
# # print(keys)

# for i,j in zip(keys,vectors):
#   print(i,':',j) # three on 1st column and corresponding numbers are its features(rows)

[[-5.4059294e-04  2.8702759e-04  5.1420662e-03 ... -7.0635420e-03
   8.9675700e-04  6.3677533e-03]
 [-8.5940203e-03  3.7575022e-03  5.2502500e-03 ... -2.3534715e-03
  -9.5351199e-03  4.3793255e-03]
 [ 9.4292649e-05  3.0885313e-03 -6.8086283e-03 ...  5.1787484e-04
   8.2049835e-03 -7.0299525e-03]
 ...
 [ 8.7977471e-03 -2.2702930e-03  4.3723010e-03 ...  6.2255617e-03
  -2.4047238e-03  9.0513807e-03]
 [-8.3833700e-03  7.9898397e-03  6.4259679e-03 ... -7.4522272e-03
   6.8071601e-03  5.6472314e-03]
 [-5.6387754e-03  3.8240075e-03  1.2600153e-03 ...  9.5440540e-03
  -9.7728651e-03 -8.9434078e-03]]


In [ ]:
vector = model.wv['dutch']
vector

array([ 1.1474404e-03,  6.1967769e-03, -6.5785618e-03,  6.5484634e-03,
        9.8149898e-03,  3.6028207e-03,  3.4593630e-03,  4.2726416e-03,
       -1.9831865e-03, -8.1459144e-03,  1.4639996e-03,  8.5256476e-04,
       -6.8098814e-03,  2.0000807e-03,  5.4872776e-03, -7.1770088e-03,
        2.5036207e-03,  7.7639390e-03, -8.6506344e-03,  3.4505632e-03,
       -8.5237846e-03, -7.9418756e-03,  7.1275802e-03, -7.6128142e-03,
       -1.4060525e-03, -7.9396321e-03, -7.9229940e-03, -7.0795487e-03,
        4.1258970e-04,  1.7904754e-03, -7.8827441e-03, -8.0592670e-03,
       -3.1424868e-03, -1.8687387e-03, -6.1731865e-03, -4.2188377e-03,
        3.6097805e-03,  3.0773771e-03,  6.5994258e-03,  4.2274855e-03,
       -8.5819495e-04,  2.7486631e-03,  9.0518063e-03,  1.9362376e-03,
        1.8286335e-03,  1.1452384e-03, -9.3262047e-03,  5.3621479e-03,
        5.0481204e-03,  6.7343812e-05,  9.2613176e-03, -5.7564662e-03,
        3.2835314e-03, -7.8469701e-03, -8.9222025e-03,  2.0596464e-03,
      

In [ ]:
# Most similar words
similar = model.wv.most_similar('war')
similar

[('rate', 0.1720738261938095),
 ('’', 0.15882465243339539),
 ('professor', 0.15752416849136353),
 ('material', 0.1459617018699646),
 ('great', 0.14304539561271667),
 ('unless', 0.14020974934101105),
 ('us', 0.12788502871990204),
 ('looted', 0.12448824942111969),
 ('self-reliant', 0.1218823567032814),
 ('worked', 0.11109071969985962)]

In [1]:
#Word Embedding
#We specify the dims for a word in embedding layer. Many such embedding layer will form Features Representation

Word Embedding Techniques using Embedding Layer in Keras

In [2]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
### Vocabulary size
voc_size=10000

One Hot Representation

In [5]:
onehot_repr=[one_hot(words,voc_size)for words in sent]  # based on words and vocab size, OHE will give index size
print(onehot_repr)

[[4092, 6735, 2781, 688], [4092, 6735, 2781, 4933], [4092, 9716, 2781, 8712], [5826, 2161, 5522, 1055, 7949], [5826, 2161, 5522, 1055, 1764], [1161, 4092, 6566, 2781, 7940], [6437, 6653, 4364, 1055]]


Passing OHE into Word Embedding Represntation

In [15]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences #to match sentence length in embedding layer
from tensorflow.keras.models import Sequential
import numpy as np

In [16]:
sent_length=8 #max sentence length
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length) #pre is add zeros before to match 8 words sentence, change to 'post'
print(embedded_docs)

[[   0    0    0    0 4092 6735 2781  688]
 [   0    0    0    0 4092 6735 2781 4933]
 [   0    0    0    0 4092 9716 2781 8712]
 [   0    0    0 5826 2161 5522 1055 7949]
 [   0    0    0 5826 2161 5522 1055 1764]
 [   0    0    0 1161 4092 6566 2781 7940]
 [   0    0    0    0 6437 6653 4364 1055]]


In [17]:
dim=10

In [19]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length)) # Feature Representation of Words
model.compile('adam','mse')

In [20]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [12]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 118ms/step
[[[ 8.64313915e-03 -7.54658133e-03  3.85131948e-02  3.91105562e-03
   -3.71877924e-02  4.68277223e-02 -1.95779689e-02  4.62418534e-02
    2.24379040e-02 -3.06661017e-02]
  [ 8.64313915e-03 -7.54658133e-03  3.85131948e-02  3.91105562e-03
   -3.71877924e-02  4.68277223e-02 -1.95779689e-02  4.62418534e-02
    2.24379040e-02 -3.06661017e-02]
  [ 8.64313915e-03 -7.54658133e-03  3.85131948e-02  3.91105562e-03
   -3.71877924e-02  4.68277223e-02 -1.95779689e-02  4.62418534e-02
    2.24379040e-02 -3.06661017e-02]
  [ 8.64313915e-03 -7.54658133e-03  3.85131948e-02  3.91105562e-03
   -3.71877924e-02  4.68277223e-02 -1.95779689e-02  4.62418534e-02
    2.24379040e-02 -3.06661017e-02]
  [ 1.32808350e-02 -4.91882451e-02  2.35729553e-02  4.12579440e-02
   -5.44596836e-03  3.78148220e-02 -2.04640757e-02  9.03892517e-03
    4.11546566e-02 -3.56959179e-03]
  [ 2.41634361e-02 -4.70392704e-02  4.25758399e-02 -1.97589155e-02
   -4.10336144e-02  8.20478052

In [22]:
embedded_docs[0] # individual words as OHE index Representation
# 1st 0 is representated by [0.02074809  0.01422128 -0.00158076  0.04260482  0.03743099 -0.02744939 0.02690974 -0.01379747 -0.03206321 -0.03500722]
# 1st 4 are going to be same
# last 688 -> [ 0.02923429  0.03882506 -0.02096164 -0.04938703  0.00778998  0.04115139 0.04665769 -0.0258477  -0.0281279  -0.04491217]

array([   0,    0,    0,    0, 4092, 6735, 2781,  688], dtype=int32)

In [23]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 76ms/step
[[ 0.02074809  0.01422128 -0.00158076  0.04260482  0.03743099 -0.02744939
   0.02690974 -0.01379747 -0.03206321 -0.03500722]
 [ 0.02074809  0.01422128 -0.00158076  0.04260482  0.03743099 -0.02744939
   0.02690974 -0.01379747 -0.03206321 -0.03500722]
 [ 0.02074809  0.01422128 -0.00158076  0.04260482  0.03743099 -0.02744939
   0.02690974 -0.01379747 -0.03206321 -0.03500722]
 [ 0.02074809  0.01422128 -0.00158076  0.04260482  0.03743099 -0.02744939
   0.02690974 -0.01379747 -0.03206321 -0.03500722]
 [ 0.0317749  -0.00259344 -0.02102555 -0.02585248  0.00384589 -0.01401185
   0.02725497  0.04022573 -0.03404214  0.03094122]
 [ 0.02649177 -0.04695528  0.00439129 -0.00904882  0.04713397  0.00892079
  -0.01204731  0.04656347 -0.01546475  0.01274537]
 [-0.01856619  0.01772969  0.0313442  -0.00370792  0.04882068  0.00047197
  -0.03966477  0.01218734  0.04448972 -0.01093228]
 [ 0.02923429  0.03882506 -0.02096164 -0.04938703  0.00778998  0.04115139